FROM scratch

ENV K8SWORKSHOPDEMO_LOCAL_HOST 0.0.0.0
ENV K8SWORKSHOPDEMO_LOCAL_PORT 8080
ENV K8SWORKSHOPDEMO_LOG_LEVEL 0

EXPOSE $K8SWORKSHOPDEMO_LOCAL_PORT

COPY certs /etc/ssl/
COPY bin/linux-amd64/k8s-workshop-demo /

CMD ["/k8s-workshop-demo"]
